---
- name: This Playbook install packages
  hosts: all
  become: true
  tasks:
  - name: install package in RHEL
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: Start httpd

  - name: install apache2
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"
    notify: start apache2

  handlers:
  - name: Start httpd
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
